### ISSUE TITLE
Field duplicated in output_stations.sql

### ISSUE THREAD

**Issue by ben2525** [mpmenne/metrolink-stl-data#4]
Mike,

The field stop_id is in the select statement twice.  Three other fields were not included in the statement, although I don't see where they would used in your code, so their inclusion would have no effect.  Also, deleting the duplicate field would affect export_to_csv.sh.  I don't know if you would want a change made so I'm not submitting a pull request.  Just an FYI.

**Comment by mpmenne** [comment]
Ben good catch.  In the app I'm importing all of these with in their current order so to keep things simple  I'll just leave the duplicate for now.
